schema_version: 20180708
name: validation
version: 0.0.109
runtime: python
build_image: fnproject/python:3.11-dev
run_image: fnproject/python:3.11
entrypoint: /python/bin/fdk /function/func.py handler
memory: 256
triggers:
- name: validation
  type: http
  source: /validation
